# Generated by Django 4.2.30 on 2026-05-23 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0010_alter_paiement_statut'),
        ('factures', '0004_alter_facture_commande_alter_facture_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='paiements.paiement'),
        ),
    ]
