# Generated by Django 4.2.30 on 2026-06-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0005_alter_facture_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='date_emission',
        ),
    ]
