# Generated by Django 4.2.30 on 2026-06-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0010_alter_paiement_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En_attente'), ('RECU', 'Reçu'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=50),
        ),
    ]
