services:
  - type: web
    name: apmthr-app
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn app_apmthr.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
